---
title: "Testing Reticulate for Keras"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install Reticulate

First I'll prove that I'm running $\texttt{R}$.

```{r cars}
library("tidyverse")

plot(c(rnorm(40), rnorm(40, 2, 1)), type = "l", ylab = "Data with mean shift")
```

Set up reticulate to use my Anaconda environment. 

```{r}
library("reticulate")

use_condaenv("/home/ubuntu/miniconda3/envs/deep-learning-03")
```

## Trying to use Python

Import python libraries

```{python}
import numpy as np
import tensorflow as tf
#import pandas as pd

from tensorflow import keras
from tensorflow.keras import layers
```

Make a training and testing set in python for function.

```{python}
# The 2D Function we are modeling 
def F_mv(x1, x2):
  return np.sin(3.14*x1/2.0)*np.cos(3.14*x2/4.0)
  
# Generate Training Data
A = 2
nb_samples = 1000
X_train = np.random.uniform(-A, A, (nb_samples, 2))
Y_train = np.zeros((nb_samples, 1))

for i in range(nb_samples):
  Y_train[i] = [F_mv(X_train[i][0], X_train[i][1])]
```

Design NN for approximating F_mv.

```{python}

# Design NN
model = keras.Sequential()

model.add(layers.Dense(30, activation="relu", input_shape = (2, )))
model.add(layers.Dense(30, activation="relu"))
model.add(layers.Dense(30, activation="relu"))
model.add(layers.Dense(1))

# Display Architerture
model.summary()

```

Compile and train NN.

```{python}

# Compile NN
model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.01),
              loss=keras.losses.MeanSquaredError())
              
# Train NN
model_history = model.fit(X_train, Y_train, epochs = 20, batch_size=500, verbose=0)
```

Prepare for graphing in R.

```{r}
# Vizualizing Function
F_mv <- function(x1, x2) sin(3.14*x1/2.0)*cos(3.14*x2/4.0)

dat_grid <- expand_grid(
  X1 = seq(-py$A, py$A, length.out = 101),
  X2 = seq(-py$A, py$A, length.out = 101))

dat_viz <- dat_grid %>% 
  mutate(Y_true = F_mv(X1, X2))

dat_grid <- as.matrix(dat_grid)
```

Make predictions in python.

```{python}
Y_viz = model.predict(r.dat_grid)
```

Visualizing predictions in R.
```{r}
# NN Visualization df
dat_viz_NN <-
  dat_viz %>% 
  add_column(Y_NN = py$Y_viz) %>% 
  pivot_longer(3:4)

dat_viz_NN %>% 
  ggplot(aes(X1, X2, fill = value)) +
  geom_raster() +
  coord_fixed(xlim = c(-2, 2), ylim = c(-2, 2), expand = FALSE) +
  scale_fill_viridis_c() +
  facet_grid(~ name)
```